apps-master/conference/Pages/Admin/Conference.cshtml.cs
using apps.Context;
using apps.Models;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace apps.Pages.Admin
{
    public class ConferenceModel : PageModel
    {
        private readonly ConferenceContext _context;

        public ConferenceModel(ConferenceContext context)
        {
            _context = context;
        }

        public IList<Bootcamp> Bootcamp { get; set; }
        public IList<Exhibitor> Exhibitor { get; set; }
        public IList<Expo> Expo { get; set; }
        public IList<Speaker> Speaker { get; set; }
        public IList<Vendor> Vendor { get; set; }

        public IList<FunNight> FunNight { get; set; }

        public async Task OnGetAsync()
        {
            Bootcamp = await _context.Bootcamps.OrderByDescending(x => x.Id).ToListAsync();
            Exhibitor = await _context.Exhibitors.OrderByDescending(i => i.Id).ToListAsync();
            Expo = await _context.Expos.OrderByDescending(i => i.Id).ToListAsync();
            Speaker = await _context.Speakers.OrderByDescending(i => i.Id).ToListAsync();
            Vendor = await _context.Vendors.OrderByDescending(i => i.Id).ToListAsync();
            FunNight = await _context.FunNights.OrderByDescending(i => i.Id).ToListAsync();

        }

        public IActionResult OnPostFunNightExcel()
        {
            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("FunNight");
                var headers = worksheet.Range("A1:R1");
                headers.Style.Font.Bold = true;
                headers.Style.Fill.BackgroundColor = XLColor.Aqua;
                worksheet.Rows(1, 2).Style.Alignment.WrapText = true;

                worksheet.Rows(1, 2).AdjustToContents();
                worksheet.Columns(1, 18).AdjustToContents();
                var currentRow = 1;

                worksheet.Cell(currentRow, 1).Value = "ROWID";
                worksheet.Cell(currentRow, 2).Value = "NPI_NUMBER";
                worksheet.Cell(currentRow, 3).Value = "FIRST_NAME";
                worksheet.Cell(currentRow, 4).Value = "LAST_NAME";
                worksheet.Cell(currentRow, 5).Value = "BADGE";
                worksheet.Cell(currentRow, 6).Value = "TITLE"; 
                worksheet.Cell(currentRow, 7).Value = "ADDRESS";
                worksheet.Cell(currentRow, 8).Value = "CITY";
                worksheet.Cell(currentRow, 9).Value = "PROVINCE";
                worksheet.Cell(currentRow, 10).Value = "POSTAL_CODE";
                worksheet.Cell(currentRow, 11).Value = "EMAIL";
                worksheet.Cell(currentRow, 12).Value = "EMERG_CONTACT_NAME";
                worksheet.Cell(currentRow, 13).Value = "EMERG_CONTACT_PHONE";
                worksheet.Cell(currentRow, 14).Value = "ACCESSIBILITY";
                worksheet.Cell(currentRow, 15).Value = "FIRST_NPI_CONFERENCE";
                worksheet.Cell(currentRow, 16).Value = "CAN_SOLICIT";



                foreach (var funNight in _context.FunNights.ToList())
                {
                    currentRow++;
                    worksheet.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
                    worksheet.Cell(currentRow, 1).Value = funNight.Id;
                    worksheet.Cell(currentRow, 2).Value = funNight.NpiNumber;
                    worksheet.Cell(currentRow, 3).Value = funNight.FirstName;
                    worksheet.Cell(currentRow, 4).Value = funNight.LastName;
                    worksheet.Cell(currentRow, 5).Value = funNight.BadgeName;
                    worksheet.Cell(currentRow, 6).Value = funNight.Title; 
                    worksheet.Cell(currentRow, 7).Value = funNight.Address;
                    worksheet.Cell(currentRow, 8).Value = funNight.City;
                    worksheet.Cell(currentRow, 9).Value = funNight.Province;
                    worksheet.Cell(currentRow, 10).Value =funNight.PostalCode;
                    worksheet.Cell(currentRow, 11).Value =funNight.Email;
                    worksheet.Cell(currentRow, 12).Value =funNight.EmergencyContactName;
                    worksheet.Cell(currentRow, 13).Value =funNight.EmergencyContactPhoneNumber;
                    worksheet.Cell(currentRow, 14).Value =funNight.AccessibilityRequirements;
                    worksheet.Cell(currentRow, 15).Value =funNight.FirstNPIConference;
                    worksheet.Cell(currentRow, 16).Value =funNight.Distribute;
                }

                using (var stream = new MemoryStream())
                {

                    workbook.SaveAs(stream);
                    var content = stream.ToArray();

                    return File(
                        content,
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        "FunNightRegistrations.xlsx");
                }
            }
        }

        public IActionResult OnPostBootcampExcel()
        {
            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Bootcamp");
                var headers = worksheet.Range("A1:R1");
                headers.Style.Font.Bold = true;
                headers.Style.Fill.BackgroundColor = XLColor.Aqua;
                worksheet.Rows(1, 2).Style.Alignment.WrapText = true; 

                worksheet.Rows(1,2).AdjustToContents();
                worksheet.Columns(1, 18).AdjustToContents();
                var currentRow = 1;
                
                worksheet.Cell(currentRow, 1).Value = "ROWID";
                worksheet.Cell(currentRow, 2).Value = "NPI_NUMBER";
                worksheet.Cell(currentRow, 3).Value = "FIRST_NAME";
                worksheet.Cell(currentRow, 4).Value = "LAST_NAME";
                worksheet.Cell(currentRow, 5).Value = "BADGE";
                worksheet.Cell(currentRow, 6).Value = "TITLE";
                worksheet.Cell(currentRow, 7).Value = "ORGANIZATION";
                worksheet.Cell(currentRow, 8).Value = "ORGANIZATION_SIZE";
                worksheet.Cell(currentRow, 9).Value = "ADDRESS";
                worksheet.Cell(currentRow, 10).Value = "CITY";
                worksheet.Cell(currentRow, 11).Value = "PROVINCE";
                worksheet.Cell(currentRow, 12).Value = "POSTAL_CODE";
                worksheet.Cell(currentRow, 13).Value = "EMAIL";
                worksheet.Cell(currentRow, 14).Value = "EMERG_CONTACT_NAME";
                worksheet.Cell(currentRow, 15).Value = "EMERG_CONTACT_PHONE";
                worksheet.Cell(currentRow, 16).Value = "ACCESSIBILITY";
                worksheet.Cell(currentRow, 17).Value = "FIRST_NPI_CONFERENCE";
                worksheet.Cell(currentRow, 18).Value = "CAN_SOLICIT"; 



                foreach (var bootcamp in _context.Bootcamps.ToList())
                {
                    currentRow++;
                    worksheet.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
                    worksheet.Cell(currentRow, 1).Value =  bootcamp.Id;
                    worksheet.Cell(currentRow, 2).Value =  bootcamp.NpiNumber;
                    worksheet.Cell(currentRow, 3).Value =  bootcamp.FirstName;
                    worksheet.Cell(currentRow, 4).Value =  bootcamp.LastName;
                    worksheet.Cell(currentRow, 5).Value =  bootcamp.BadgeName;
                    worksheet.Cell(currentRow, 6).Value =  bootcamp.Title;
                    worksheet.Cell(currentRow, 7).Value =  bootcamp.Organization;
                    worksheet.Cell(currentRow, 8).Value =  bootcamp.NumberOfEmployees;
                    worksheet.Cell(currentRow, 9).Value =  bootcamp.Address; 
                    worksheet.Cell(currentRow, 10).Value = bootcamp.City;
                    worksheet.Cell(currentRow, 11).Value = bootcamp.Province;
                    worksheet.Cell(currentRow, 12).Value = bootcamp.PostalCode;
                    worksheet.Cell(currentRow, 13).Value = bootcamp.Email;
                    worksheet.Cell(currentRow, 14).Value = bootcamp.EmergencyContactName;
                    worksheet.Cell(currentRow, 15).Value = bootcamp.EmergencyContactPhoneNumber;
                    worksheet.Cell(currentRow, 16).Value = bootcamp.AccessibilityRequirements;
                    worksheet.Cell(currentRow, 17).Value = bootcamp.FirstNPIConference;
                    worksheet.Cell(currentRow, 18).Value = bootcamp.Distribute;
                }

                using (var stream = new MemoryStream())
                {

                    workbook.SaveAs(stream);
                    var content = stream.ToArray();

                    return File(
                        content,
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        "BootcampRegistrations.xlsx");
                }
            }
        } 


        public IActionResult OnPostExhibitorExcel()
        {
            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Exhibitors");
                var headers = worksheet.Range("A1:R1");
                headers.Style.Font.Bold = true;
                headers.Style.Fill.BackgroundColor = XLColor.Aqua;
                worksheet.Rows(1, 2).Style.Alignment.WrapText = true;

                worksheet.Rows(1, 2).AdjustToContents();
                worksheet.Columns(1, 18).AdjustToContents();
                var currentRow = 1;

                worksheet.Cell(currentRow, 1).Value = "ROWID";
                worksheet.Cell(currentRow, 2).Value = "NPI_NUMBER";
                worksheet.Cell(currentRow, 3).Value = "FIRST_NAME";
                worksheet.Cell(currentRow, 4).Value = "LAST_NAME";
                worksheet.Cell(currentRow, 5).Value = "BADGE";
                worksheet.Cell(currentRow, 6).Value = "TITLE";

apps-master/conference/Pages/Admin/Conference.cshtml
@page
@model apps.Pages.Admin.ConferenceModel
@{
    ViewData["Title"] = "Conference Exports";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class='container'>

    <!-- bootcamps  -->
    <div class='row'>
        <div class='col'>
            <div class='my-2 mb-4' style='float:right;'>
            </div>
            <div class='mt-4'>
                <h1 class='fs-2'>Registrations</h1>
            </div>

            <div class="row">
                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="p-4 text-center bg-white shadow-sm rounded">
                        <div class="d-inline-block py-3 px-4 bg-light rounded-circle text-primary fw-bold">1</div> 
                        <h5 class="mb-3">Bootcamp Registrations</h5>
                        <div class='alert alert-info p-1'>
                            <p>There are/is @Model.Bootcamp.Count registration(s).</p>
                        </div>
                         <form method="post">
                            <button asp-page-handler="BootcampExcel" class='btn btn-info float-right'>
                                Download Excel File <i data-feather="download"></i>
                            </button>
                        </form>
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="p-4 text-center bg-white shadow-sm rounded">
                        <div class="d-inline-block py-3 px-4 bg-light rounded-circle text-primary fw-bold">2</div> 
                        <h5 class="mb-3">Exhibitor Registrations</h5>
                        <div class='alert alert-info p-1'>
                            <p>There are/is @Model.Exhibitor.Count registration(s).</p>
                        </div>
                         <form method="post">
                            <button asp-page-handler="ExhibitorExcel" class='btn btn-info float-right'>
                                Download Excel File <i data-feather="download"></i>
                            </button>
                        </form>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="p-4 text-center bg-white shadow-sm rounded">
                        <div class="d-inline-block py-3 px-4 bg-light rounded-circle text-primary fw-bold">3</div> 
                        <h5 class="mb-3">Expo Registrations</h5>
                        <div class='alert alert-info p-1'>
                            <p>There are/is @Model.Expo.Count registration(s).</p>
                        </div>
                         <form method="post">
                            <button asp-page-handler="ExpoExcel" class='btn btn-info float-right'>
                                Download Excel File <i data-feather="download"></i>
                            </button>
                        </form>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="p-4 text-center bg-white shadow-sm rounded">
                        <div class="d-inline-block py-3 px-4 bg-light rounded-circle text-primary fw-bold">4</div> 
                        <h5 class="mb-3">Speaker Registrations</h5>
                        <div class='alert alert-info p-1'>
                            <p>There are/is @Model.Speaker.Count registration(s).</p>
                        </div>
                         <form method="post">
                            <button asp-page-handler="SpeakerExcel" class='btn btn-info float-right'>
                                Download Excel File <i data-feather="download"></i>
                            </button>
                        </form>
                    </div>
                </div>

                 <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="p-4 text-center bg-white shadow-sm rounded">
                        <div class="d-inline-block py-3 px-4 bg-light rounded-circle text-primary fw-bold">
                            5
                        </div> 
                        <h5 class="mb-3">Vendor Registrations</h5>
                        <div class='alert alert-info p-1'>
                            <p>There are/is @Model.Vendor.Count registration(s).</p>
                        </div>
                         <form method="post">
                            <button asp-page-handler="VendorExcel" class='btn btn-info float-right'>
                                Download Excel File <i data-feather="download"></i>
                            </button>
                        </form>
                    </div>
                </div>

                 <div class="col-12 col-md-6 col-lg-3 mb-4">
                    <div class="p-4 text-center bg-white shadow-sm rounded">
                        <div class="d-inline-block py-3 px-4 bg-light rounded-circle text-primary fw-bold">
                            6
                        </div> 
                        <h5 class="mb-3">Fun Night Registrations</h5>
                        <div class='alert alert-info p-1'>
                            <p>There are/is @Model.FunNight.Count registration(s).</p>
                        </div>
                         <form method="post">
                            <button asp-page-handler="FunNightExcel" class='btn btn-info float-right'>
                                Download Excel File <i data-feather="download"></i>
                            </button>
                        </form>
                    </div>
                </div>                


            </div>

        </div>
    </div>

</div> 

apps-master/conference/Pages/Admin/TMp.cshtml
@page
@model apps.Pages.Admin.TmpModel
@{
    ViewData["Title"] = "Conference Exports";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}




<div class='container'>

     <!-- bootcamps  -->
    <div class='row'>
        <div class='col'>
            <div class='my-2 mb-4' style='float:right;'>
                <form method="post">
                    <button asp-page-handler="BootcampExcel" class='btn btn-info float-right'>
                        Download Complete Excel File <i data-feather="download"></i>
                    </button>
                </form>
            </div>
            <div class='mt-4'>
                <h1 class='fs-2'>Bootcamp Registrations</h1>
            </div>

            <table class='dataTable'>
                <thead>
                    <tr>
                        <th>Row ID</th>
                        <th>NPI Number</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Name for Badge</th>
                        <th>Organization</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var registration in Model.Bootcamp)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => registration.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => registration.NpiNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => registration.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => registration.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => registration.BadgeName)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => registration.Organization)
                            </td>

                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>

    <!-- exhibitors -->
    <div class='row'>
        <div class='col'>
            <div class='my-2 mb-4' style='float:right;'>
                <form method="post">
                    <button asp-page-handler="ExhibitorExcel" class='btn btn-info float-right'>
                        Download Complete Excel File <i data-feather="download"></i>
                    </button>
                </form>
            </div>
            <div class='mt-4'>
                <h1 class='fs-2'>Exhibitor Registrations</h1>
            </div>

            <table class='dataTable'>
                <thead>
                    <tr>
                        <th>Row ID</th>
                        <th>NPI Number</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Name for Badge</th>
                        <th>Organization</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var exhibitor in Model.Exhibitor)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => exhibitor.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => exhibitor.NpiNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => exhibitor.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => exhibitor.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => exhibitor.BadgeName)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => exhibitor.Organization)
                            </td>

                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
    

    <!-- expo -->
    <div class='row'>
        <div class='col'>
            <div class='my-2 mb-4' style='float:right;'>
                <form method="post">
                    <button asp-page-handler="ExpoExcel" class='btn btn-info float-right'>
                        Download Complete Excel File <i data-feather="download"></i>
                    </button>
                </form>
            </div>
            <div class='mt-4'>
                <h1 class='fs-2'>Expo Registrations</h1>
            </div>

            <table class='dataTable'>
                <thead>
                    <tr>
                        <th>Row ID</th>
                        <th>NPI Number</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Name for Badge</th>
                        <th>Organization</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var registration in Model.Expo)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => registration.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => registration.NpiNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => registration.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => registration.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => registration.BadgeName)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => registration.Organization)
                            </td>

                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>


    <!--speakers-->
    <div class='row'>
        <div class='col'>
            <div class='my-2 mb-4' style='float:right;'>
                <form method="post">
                    <button asp-page-handler="BootcampExcel" class='btn btn-info float-right'>
                        Download Complete Excel File <i data-feather="download"></i>
                    </button>
                </form>
            </div>
            <div class='mt-4'>
                <h1 class='fs-2'>Speaker Registrations</h1>
            </div>

            <table class='dataTable'>
                <thead>
                    <tr>
                        <th>Row ID</th>
                        <th>NPI Number</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Name for Badge</th>
                        <th>Speaking Date</th>
                        <th>Organization</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var speaker in Model.Speaker)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => speaker.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => speaker.NpiNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => speaker.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => speaker.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => speaker.BadgeName)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => speaker.SpeakingDate)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => speaker.Organization)
                            </td>

                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</div> 